ALGO:
Love bug is going around - every inhabitant is in love

You can buy strawberries, chocolate, or roses

You can buy a gift basket that has 6 strawberries, 4 chocolates, and a rose

If the gift basket won't impress, aim your arrows in another direction


MANUAL:
Treasure map by iguanas

Note:
My precious map reveals where all the tropical treasures are to be found. Some laying on the surface and others buried deep into the ground.

Your first expedition will cost you no fee, but the second one comes at a price and the third is times three.

You'll share the spoils with everyone that marks the same spot. So you might be wise to choose a destination less hot.

On you go, mark your spot and find your treasure. But remember that this is about serious Seashell business, no leisure.




The map shows that bounty is scattered all over the archepelago.Treasure chests each have 7.5k seashells and there are multiple chests potentially hidden in one location (a.k.a multiplier). 

Keep in mind that you are not the only one searching and youâ€™ll have to split the spoils with all the others that search in the same spot. Plan your expeditions carefully and you might return with the biggest loot of all. 

Here's a breakdown of how your profit from an expedition will be computed:
Every spot has its **treasure multiplier** (up to 100) and the number of **hunters** (up to 8). The spot's total treasure is the product of the **base treasure** (7500, same for all spots) and the spot's specific treasure multiplier. However, the resulting amount is then divided by the sum of the hunters and the percentage of all the expeditions (from other players) that took place there. For example, if a field has 5 hunters, and 10% of all the expeditions (from all the other players) are also going there, the prize you get from that field will be divided by 15. After the division, **expedition costs** apply (if there are any), and profit is what remains.

Second and third expeditions are optional: you are not required to do all 3. Order of submitted expeditions does not matter for grading.

All expeditions from everyone are aggregated and that's how percentages per tile are decided

OK for manual there must be some hidden messages found in that note.

My precious map reveals where all the tropical treasures are to be found. Some laying on the surface and others buried deep into the ground.

Your first expedition will cost you no fee, but the second one comes at a price and the third is times three.

You'll share the spoils with everyone that marks the same spot. So you might be wise to choose a destination less hot.

On you go, mark your spot and find your treasure. But remember that this is about serious Seashell business, no leisure.


MSYYSOBS
tropical treasures, times three, serious Seashell




Also, we basically just guessing human psychology lmao, straight up just kind of luck

lowkey make like 1000 accounts and just ruin every one elses choices except ours

In [3]:
# Calculating net profit for each spot for first, second, and third expeditions without competition
all_spot_profits = {}
expedition_costs = [0, 25000, 75000]
base_treasure = 7500
map_data = {
    'G26': {'multiplier': 24, 'hunters': 2},
    'G27': {'multiplier': 70, 'hunters': 4},
    'G28': {'multiplier': 41, 'hunters': 3},
    'G29': {'multiplier': 21, 'hunters': 2},
    'G30': {'multiplier': 60, 'hunters': 4},
    'H26': {'multiplier': 47, 'hunters': 3},
    'H27': {'multiplier': 82, 'hunters': 5},
    'H28': {'multiplier': 87, 'hunters': 5},
    'H29': {'multiplier': 80, 'hunters': 5},
    'H30': {'multiplier': 35, 'hunters': 3},
    'I26': {'multiplier': 73, 'hunters': 4},
    'I27': {'multiplier': 89, 'hunters': 5},
    'I28': {'multiplier': 100, 'hunters': 8},
    'I29': {'multiplier': 90, 'hunters': 7},
    'I30': {'multiplier': 17, 'hunters': 2},
    'J26': {'multiplier': 77, 'hunters': 5},
    'J27': {'multiplier': 83, 'hunters': 5},
    'J28': {'multiplier': 85, 'hunters': 5},
    'J29': {'multiplier': 79, 'hunters': 5},
    'J30': {'multiplier': 55, 'hunters': 4},
    'K26': {'multiplier': 12, 'hunters': 2},
    'K27': {'multiplier': 27, 'hunters': 3},
    'K28': {'multiplier': 52, 'hunters': 4},
    'K29': {'multiplier': 15, 'hunters': 2},
    'K30': {'multiplier': 30, 'hunters': 3}
}

for spot, data in map_data.items():
    total_treasure = base_treasure * data['multiplier']
    treasure_per_hunter = total_treasure / data['hunters']
    net_profit_first = treasure_per_hunter  # First expedition is free
    net_profit_second = treasure_per_hunter - expedition_costs[1]
    net_profit_third = treasure_per_hunter - expedition_costs[2]
    all_spot_profits[spot] = {
        'Net Profit First': net_profit_first,
        'Net Profit Second': net_profit_second,
        'Net Profit Third': net_profit_third
    }

# Sort by the highest profit scenarios for first, second, and third expeditions
sorted_first = sorted(all_spot_profits.items(), key=lambda x: x[1]['Net Profit First'], reverse=True)
sorted_second = sorted(all_spot_profits.items(), key=lambda x: x[1]['Net Profit Second'], reverse=True)
sorted_third = sorted(all_spot_profits.items(), key=lambda x: x[1]['Net Profit Third'], reverse=True)

# Top three spots for maximum potential profit, considering first, second, and third expeditions
top_first = sorted_first[:3]
top_second = sorted_second[:3]
top_third = sorted_third[:3]

top_first, top_second, top_third

([('I26',
   {'Net Profit First': 136875.0,
    'Net Profit Second': 111875.0,
    'Net Profit Third': 61875.0}),
  ('I27',
   {'Net Profit First': 133500.0,
    'Net Profit Second': 108500.0,
    'Net Profit Third': 58500.0}),
  ('G27',
   {'Net Profit First': 131250.0,
    'Net Profit Second': 106250.0,
    'Net Profit Third': 56250.0})],
 [('I26',
   {'Net Profit First': 136875.0,
    'Net Profit Second': 111875.0,
    'Net Profit Third': 61875.0}),
  ('I27',
   {'Net Profit First': 133500.0,
    'Net Profit Second': 108500.0,
    'Net Profit Third': 58500.0}),
  ('G27',
   {'Net Profit First': 131250.0,
    'Net Profit Second': 106250.0,
    'Net Profit Third': 56250.0})],
 [('I26',
   {'Net Profit First': 136875.0,
    'Net Profit Second': 111875.0,
    'Net Profit Third': 61875.0}),
  ('I27',
   {'Net Profit First': 133500.0,
    'Net Profit Second': 108500.0,
    'Net Profit Third': 58500.0}),
  ('G27',
   {'Net Profit First': 131250.0,
    'Net Profit Second': 106250.0,
    'Net Profit Third': 56250.0})])